server:
  port: 8080

logging:
  level:
    root: info
    org.springframework.web: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_practice
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    jdbc:
      dialect: mysql