server:
  port: 8080

logging:
  level:
    root: info
#    org.springframework.web: debug
#    org.springframework.security: debug

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
    display-request-duration: true
    oauth:
      client-id: ${KAKAO_CLIENT_ID}
      client-secret: ${KAKAO_CLIENT_SECRET}
  default-consumes-media-type: application/json

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_practice
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    jdbc:
      dialect: mysql
  security:
    oauth2:
      # 아래 정보 대신 ClientRegistration을 활용할 수 있다.
      client:
        provider: # OAuth2 서비스 정보
          kakao:
            authorization-uri: ${KAKAO_AUTH_URI} # 로그인 창 URI
            token-uri: ${KAKAO_TOKEN_URI} # 클라이언트가 토큰을 요청할 인증 서버 URI
            user-info-uri: ${KAKAO_INFO_URI} # 리소스 서버 URL
            user-info-authentication-method: header # header, form, query. header는 헤더에 토큰을 넣어 전송.
            user-name-attribute: id # 응답 데이터 변수(key 값)
        registration: # 내 서비스 정보
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post # 토큰 요청 방법. c_s_p는 client_id와 client_secret을 이용해 요청한다.
            redirect-uri: ${KAKAO_REDIRECT_URI} # 로그인 성공 후 리다이렉트할 URI, 즉, 인증 코드를 받을 URI.
            authorization-grant-type: authorization_code
            client-name: urchinode # 서비스 이름
            scope:
              - profile_nickname
              - account_email
              - gender
jwt:
  secret-key: ${JWT_KEY}

KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
KAKAO_AUTH_REQ_URL: ${KAKAO_AUTH_REQ_URL}
KAKAO_TOKEN_URI: ${KAKAO_TOKEN_URI}
FRONT_URL: ${FRONT_URL}